In [5]:
import pandas as pd 
import numpy as np 
data={
    'Name':['Dhoni','Rohit','Virat','Gill'],
    'Run':[12000,11000,3000,4000],
    'Average':[59.5,48.7,51.2,45.3]
}
df=pd.DataFrame(data,index=['A','B','C','D'])
print(df)
print('-------------------------------')
print(df.shape)
print(df.size)
print(df.columns)
df.index
df.values
df[['Run','Average']]
df.loc['C','Run']=4000
print('-------------------------------')
print(df)
print('-------------------------------')
print(df.set_index(['Name']))
print('-------------------------------')
print(df.set_index(['Name','Run'],drop=False))
print('-------------------------------')
df.sort_values(by='Average',ascending=False,axis=0)

    Name    Run  Average
A  Dhoni  12000     59.5
B  Rohit  11000     48.7
C  Virat   3000     51.2
D   Gill   4000     45.3
-------------------------------
(4, 3)
12
Index(['Name', 'Run', 'Average'], dtype='object')
-------------------------------
    Name    Run  Average
A  Dhoni  12000     59.5
B  Rohit  11000     48.7
C  Virat   4000     51.2
D   Gill   4000     45.3
-------------------------------
         Run  Average
Name
Dhoni  12000     59.5
Rohit  11000     48.7
Virat   4000     51.2
Gill    4000     45.3
-------------------------------
              Name    Run  Average
Name  Run
Dhoni 12000  Dhoni  12000     59.5
Rohit 11000  Rohit  11000     48.7
Virat 4000   Virat   4000     51.2
Gill  4000    Gill   4000     45.3
-------------------------------

    Name    Run  Average
A  Dhoni  12000     59.5
C  Virat   4000     51.2
B  Rohit  11000     48.7
D   Gill   4000     45.3

In [6]:
df.sort_values(by='Average',ascending=False,axis=0)

    Name    Run  Average
A  Dhoni  12000     59.5
C  Virat   4000     51.2
B  Rohit  11000     48.7
D   Gill   4000     45.3

In [9]:
df.sort_index(axis=1)

   Average   Name    Run
A     59.5  Dhoni  12000
B     48.7  Rohit  11000
C     51.2  Virat   4000
D     45.3   Gill   4000

In [15]:
data['scrore']=[1000,2000,3000,4000]
df=pd.DataFrame(data,index=['A','B','C','D'])
print(df)
df[df['Run']>10000]

    Name    Run  Average  scrore
A  Dhoni  12000     59.5    1000
B  Rohit  11000     48.7    2000
C  Virat   3000     51.2    3000
D   Gill   4000     45.3    4000

    Name    Run  Average  scrore
A  Dhoni  12000     59.5    1000
B  Rohit  11000     48.7    2000

In [19]:
df[(df['Run']>10000)&(df['Average']>50)]

    Name    Run  Average  scrore
A  Dhoni  12000     59.5    1000

In [21]:
df[['Name','Average']][df['Average']>50]

    Name  Average
A  Dhoni     59.5
C  Virat     51.2

In [31]:
print(df.sort_values(by=['Run','Average'],ascending=[True,False],ignore_index=True,inplace=True))

None

In [32]:
import pandas as pd 
import numpy as np 
df=pd.read_csv('auto-mpg.csv')